name: Build Binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build binary with PyInstaller
        run: |
          pyinstaller --onefile --name CachyUpdate_History CachyUpdate_History.py

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: CachyUpdate_History-bin
          path: dist/CachyUpdate_History 